
package Cronometro;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;


public class Ventana extends javax.swing.JFrame {
    
    int horas=0, minutos=0, segundos=0, centesimaSegundos=0;
    Timer tiempo;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            centesimaSegundos++;
            if(centesimaSegundos == 100){
                segundos++;
                centesimaSegundos = 0;
            }
            if(segundos == 60){
                minutos++;
                segundos = 0;
            }
            if(minutos == 60){
                horas++;
                minutos = 0;
            }
            actualizarTiempo();
        }
    };

    private void actualizarTiempo(){
        String texto = (horas<=9?"0":"")+horas+":"+(minutos<=9?"0":"")+minutos+":"+(segundos<=9?"0":"")+segundos+":"+(centesimaSegundos<=9?"0":"")+centesimaSegundos;
        etiquetaTiempo.setText(texto);
    }
 
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        tiempo =  new Timer(10, acciones);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        etiquetaCronometro = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        botonIniciar = new javax.swing.JButton();
        botonPausar = new javax.swing.JButton();
        botonDetener = new javax.swing.JButton();
        etiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cronometro");
        setResizable(false);

        panel.setMaximumSize(new java.awt.Dimension(574, 574));
        panel.setMinimumSize(new java.awt.Dimension(300, 300));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaCronometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cronometro.png"))); // NOI18N
        panel.add(etiquetaCronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        etiquetaTitulo.setFont(new java.awt.Font("Cooper Black", 3, 48)); // NOI18N
        etiquetaTitulo.setText("Cronometro");
        panel.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 330, 70));

        etiquetaTiempo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTiempo.setText("00:00:00:00");
        etiquetaTiempo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panel.add(etiquetaTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 310, 80));

        botonIniciar.setBackground(new java.awt.Color(0, 204, 204));
        botonIniciar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonIniciar.setText("Start");
        botonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarActionPerformed(evt);
            }
        });
        panel.add(botonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 110, 40));

        botonPausar.setBackground(new java.awt.Color(0, 204, 204));
        botonPausar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonPausar.setText("Pause");
        botonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPausarActionPerformed(evt);
            }
        });
        panel.add(botonPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 40));

        botonDetener.setBackground(new java.awt.Color(0, 204, 204));
        botonDetener.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        botonDetener.setText("Stop");
        botonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDetenerActionPerformed(evt);
            }
        });
        panel.add(botonDetener, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 110, 40));

        etiquetaFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        panel.add(etiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDetenerActionPerformed
        if(tiempo.isRunning()){
            tiempo.stop();
            botonIniciar.setEnabled(true);
        }  
        botonIniciar.setText("Start");
        botonDetener.setEnabled(false);
        botonPausar.setEnabled(false);
        horas=0;
        minutos=0;
        segundos=0;
        centesimaSegundos=0;
        actualizarTiempo();   
    }//GEN-LAST:event_botonDetenerActionPerformed

    private void botonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarActionPerformed
        tiempo.start();
        botonIniciar.setText("Resume");
        botonIniciar.setEnabled(false);
        botonPausar.setEnabled(true);
        botonDetener.setEnabled(true);
    }//GEN-LAST:event_botonIniciarActionPerformed

    private void botonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPausarActionPerformed
        tiempo.stop();
        botonIniciar.setEnabled(true);
        botonPausar.setEnabled(false);
    }//GEN-LAST:event_botonPausarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDetener;
    private javax.swing.JButton botonIniciar;
    private javax.swing.JButton botonPausar;
    private javax.swing.JLabel etiquetaCronometro;
    private javax.swing.JLabel etiquetaFondo;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
